name: Deploy
on:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install maturin
        run: |
          python -m pip install --upgrade pip maturin
      - name: Build & Publish to PyPi
        if: matrix.os != 'windows-latest'
        run: maturin publish --username __token__ --no-sdist --interpreter python${{ matrix.python-version }} --manylinux=2014
        env:
          MATURIN_PASSWORD: ${{ secrets.pypi_password }}
      - name: Build & Publish to PyPi
        if: matrix.os == 'windows-latest'
        run: maturin publish --username=__token__ --no-sdist --interpreter=python --manylinux=2014
        env:
          MATURIN_PASSWORD: ${{ secrets.pypi_password }}
